steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/skindect/newsapi', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/skindect/newsapi']
images:
- 'gcr.io/skindect/newsapi'
